name: tizen_interop
description: Dart bindings for Tizen native APIs, powered by ffigen.
homepage: https://github.com/flutter-tizen/tizen_interop
version: 0.4.1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  ffi: ^2.0.1

dev_dependencies:
  ffigen: ^11.0.0
  lints: ^3.0.0
  symgen:
    path: packages/symgen
