name: tizen_interop
description: Provides Dart bindings and utility functions for Tizen native APIs.
version: 0.0.1
homepage: https://github.com/flutter-tizen/tizen_interop

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies: 
  ffi: ^1.1.2
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  ffigen: ^3.0.0
  symgen:
    path: packages/symgen
