# Tizen 4.0 Wearable Native Libraries

preamble: |
  // Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
  // Use of this source code is governed by a BSD-style license that can be
  // found in the LICENSE file.

name: tizen40Symbols
output: 'lib/src/bindings/4.0/wearable/generated_symbols.dart'
library-path: 'rootstraps/wearable-4.0-device.core/usr/lib'
allowlist: 'configs/4.0/wearable/allowlist.txt'
target-libraries:
  - libaccounts-svc.so.0                        # Account / Account Manager
  - libfido-client.so.0                         # Account / FIDO Client
  - liboauth2.so.0                              # Account / OAuth 2.0
  - libcore-sync-client.so.1.0                  # Account / Sync Manager
  - libcapi-appfw-application.so.0              # Applicatoin Framework / Application (include i18n)
  - libcapi-appfw-alarm.so.0                    # Application Framework / Application / Alarm
  - libcapi-appfw-app-common.so.0               # Application Framework / Application / App Common, Resource Manager
  - libcapi-appfw-app-control.so.0              # Application Framework / Application / App Control
  - libcapi-appfw-event.so.0                    # Application Framework / Application / Event
  - libcapi-appfw-job-scheduler.so.0            # Application Framework / Application / Job scheduler
  - libcapi-appfw-preference.so.0               # Application Framework / Application / Preference
  - libcapi-appfw-app-manager.so.0              # Application Framework / Application Manager
  - libbadge.so.0                               # Application Framework / Badge
  - libbundle.so.0                              # Application Framework / Bundle
  - libdata-control.so.0                        # Application Framework / Data Control
  - libmessage-port.so.1                        # Application Framework / Message Port
  - libnotification.so.0                        # Application Framework / Notification
  - libcapi-appfw-package-manager.so.0          # Application Framework / Package Manager
  - libappcore-agent.so.1                       # Application Framework / Service Application
  - libappcore-watch.so.1                       # Application Framework / Watch Application
  - libcapi-appfw-widget-application.so.1       # Application Framework / Widget / Widget Application
  - libwidget_service.so.1                      # Application Framework / Widget / Widget Service
  - libwidget_viewer_evas.so.1                  # Application Framework / Widget / Widget Viewer
  - libcapi-base-common.so.0                    # Base / Common Error
  - libcapi-content-mime-type.so.0              # Content / Mime Type
  - libcapi-content-media-content.so.0          # Content / Media Content
  - libcapi-context-motion.so.2                 # Context / Activity Recognition, Gesture Recognition
  - libcapi-context.so.1                        # Context / Contextual History
  - libcapi-location-manager.so.0               # Location / Location Manager
  - libcapi-maps-service.so.0                   # Location / Maps Service
  - libcapi-messaging-email.so.0                # Messaging / Email
  - libcapi-messaging-messages.so.0             # Messaging / Messages
  - libpush.so.0                                # Messaging / Push
  - libcapi-media-audio-io.so.0                 # Multimedia / Audio I/O
  - libcapi-media-camera.so.0                   # Multimedia / Camera
  - libcapi-media-image-util.so.0               # Multimedia / Image Util
  - libcapi-media-codec.so.0                    # Multimedia / Media Codec
  - libcapi-media-controller.so.0               # Multimedia / Media Controller
  - libcapi-mediademuxer.so.0                   # Multimedia / Media Demuxer
  - libcapi-mediamuxer.so.0                     # Multimedia / Media Muxer
  - libcapi-media-streamer.so.0                 # Multimedia / Media Streamer
  - libcapi-media-tool.so.0                     # Multimedia / Media Tool
  - libcapi-media-vision.so.0                   # Multimedia / Media Vision
  - libcapi-media-metadata-editor.so            # Multimedia / Metadata Editor
  - libcapi-media-metadata-extractor.so         # Multimedia / Metadata Extractor
  - libcapi-media-player.so.0                   # Multimedia / Player
  - libcapi-media-radio.so.0                    # Multimedia / Radio
  - libcapi-media-recorder.so.0                 # Multimedia / Recorder
  - libcapi-media-sound-manager.so.0            # Multimedia / Sound Manager
  - libcapi-media-sound-pool.so.0               # Multimedia / Sound Pool
  - libcapi-media-streamrecorder.so.0           # Multimedia / StreamRecorder
  - libcapi-media-thumbnail-util.so             # Multimedia / Thumbnail Util
  - libcapi-media-tone-player.so.0              # Multimedia / Tone Player
  - libcapi-media-wav-player.so.0               # Multimedia / WAV Player
  - libasp.so.0                                 # Network / Application Service Platform
  - libcapi-network-bluetooth.so.0              # Network / Bluetooth
  - libcapi-network-connection.so.1             # Network / Connection
  - libnsd-dns-sd.so.0                          # Network / DNSSD
  - libcapi-network-http.so.0.1.0               # Network / HTTP
  - libiotcon.so.0                              # Network / IoTCon
  - libcapi-network-nfc.so.0                    # Network / NFC
  - libnsd-ssdp.so.0                            # Network / SSDP
  - libcapi-network-stc.so.0                    # Network / Smart Traffic Control
  - libcapi-network-smartcard.so.0              # Network / Smartcard
  - libcapi-network-wifi-manager.so.1           # Network / WI-Fi Manager
  - libcsr-client.so.2                          # Security / CSR
  - libdpm.so.0                                 # Security / Device Policy Manager
  - libkey-manager-client.so.1                  # Security / Key Manager Client
  - libcapi-privacy-privilege-manager.so.0      # Security / Privacy Privilege Manager
  - libprivilege-info.so.1                      # Security / Privilege Info
  - libyaca.so.0                                # Security / YACA
  - libcalendar-service2.so.0                   # Social / Calendar
  - libcontacts-service2.so.0                   # Social / Contacts
  - libphonenumber-utils.so.0                   # Social / Phonenumber utils
  - libcapi-system-device.so.0                  # System / Device
  - libdlog.so.0                                # System / Dlog
  - libfeedback.so.0                            # System / Feedback
  - libcapi-system-media-key.so.0               # System / Media key
  - libcapi-system-runtime-info.so.0            # System / Runtime information
  - libcapi-system-sensor.so.0                  # System / Sensor
  - libstorage.so.0.1                           # System / Storage
  - libcapi-system-info.so.0                    # System / System Information
  - libcapi-system-system-settings.so.0         # System / System Settings
  - libttrace.so.1                              # System / T-trace
  - libcapi-telephony.so.0                      # Telephony / Telephony Information
  - libcapi-ui-inputmethod.so.0                 # UIX / Input Method
  - libcapi-ui-inputmethod-manager.so.0         # UIX / Input Method Manager
  - libstt.so                                   # UIX / STT
  - libstt_engine.so                            # UIX / STT Engine
  - libtts.so                                   # UIX / TTS
  - libtts_engine.so                            # UIX / TTS Engine
  - libvc.so                                    # UIX / Voice control
