name: tizen_interop_callbacks
description: Cross-thread callbacks for Tizen native APIs.
homepage: https://github.com/flutter-tizen/tizen_interop
repository: https://github.com/flutter-tizen/tizen_interop/tree/main/packages/tizen_interop_callbacks
version: 0.3.1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  tizen_log: ^0.1.2

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: TizenInteropCallbacksPlugin
        fileName: tizen_interop_callbacks_plugin.h
