preamble: |
  // Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
  // Use of this source code is governed by a BSD-style license that can be
  // found in the LICENSE file.

  // ignore_for_file: camel_case_types, non_constant_identifier_names

name: 'Tizen40Native'
description: 'Provides Dart bindings for Tizen native APIs.'
output: 'lib/src/bindings/4.0/generated_bindings.dart'

llvm-path:
  - '/usr/lib/llvm-12'

headers:
  entry-points:
    - 'configs/4.0/entrypoints.h'
  include-directives:
    - '**/bundle.h'
    - '**/inputmethod.h'
    - '**/inputmethod_manager.h'
    - '**/mtp.h'
    - '**/peripheral_io.h'
    - '**/privilege_information.h'
    - '**/smartcard.h'
    - '**/stte.h'
    - '**/stt.h'
    - '**/tbm_surface.h'
    - '**/tizen_error.h'
    - '**/tizen.h'
    - '**/trace.h'
    - '**/ttse.h'
    - '**/tts.h'
    - '**/usb_host.h'
    - '**/voice_control.h'
    - '**/appcore-agent/*.h'
    - '**/appfw/*.h'
    - '**/badge/*.h'
    - '**/calendar-service2/*.h'
    - '**/cbhm/*.h'
    - '**/ckm/ckmc/*.h'
    - '**/contacts-svc/*.h'
    - '**/content/*.h'
    - '**/csr/*.h'
    - '**/device/*.h'
    - '**/dlog/*.h'
    - '**/dpm/*.h'
    - '**/eom/*.h'
    - '**/feedback/*.h'
    - '**/iotcon/*.h'
    - '**/media/*.h'
    - '**/media-content/*.h'
    - '**/messaging/*.h'
    - '**/metadata-editor/*.h'
    - '**/network/*.h'
    - '**/notification/*.h'
    - '**/nsd/*.h'
    - '**/phonenumber-utils/*.h'
    - '**/privacy-privilege-manager/*.h'
    - '**/sensor/*.h'
    - '**/shortcut/*.h'
    - '**/storage/*.h'
    - '**/system/*.h'
    - '**/telephony/*.h'
    - '**/web/*.h'
    - '**/yaca/*.h'

compiler-opts:
  - '-m32'
  - '-Wno-incomplete-setjmp-declaration'
  - '-I./rootstraps/4.0/usr/include/'
  - '-I./rootstraps/4.0/usr/include/appcore-agent/'
  - '-I./rootstraps/4.0/usr/include/appfw/'
  - '-I./rootstraps/4.0/usr/include/badge/'
  - '-I./rootstraps/4.0/usr/include/calendar-service2/'
  - '-I./rootstraps/4.0/usr/include/cbhm/'
  - '-I./rootstraps/4.0/usr/include/ckm/'
  - '-I./rootstraps/4.0/usr/include/contacts-svc/'
  - '-I./rootstraps/4.0/usr/include/content/'
  - '-I./rootstraps/4.0/usr/include/csr/'
  - '-I./rootstraps/4.0/usr/include/dlog/'
  - '-I./rootstraps/4.0/usr/include/eom/'
  - '-I./rootstraps/4.0/usr/include/feedback/'
  - '-I./rootstraps/4.0/usr/include/iotcon/'
  - '-I./rootstraps/4.0/usr/include/media/'
  - '-I./rootstraps/4.0/usr/include/media-content/'
  - '-I./rootstraps/4.0/usr/include/messaging/'
  - '-I./rootstraps/4.0/usr/include/metadata-editor/'
  - '-I./rootstraps/4.0/usr/include/network/'
  - '-I./rootstraps/4.0/usr/include/notification/'
  - '-I./rootstraps/4.0/usr/include/nsd/'
  - '-I./rootstraps/4.0/usr/include/phonenumber-utils/'
  - '-I./rootstraps/4.0/usr/include/privacy-privilege-manager/'
  - '-I./rootstraps/4.0/usr/include/sensor/'
  - '-I./rootstraps/4.0/usr/include/shortcut/'
  - '-I./rootstraps/4.0/usr/include/storage/'
  - '-I./rootstraps/4.0/usr/include/system/'
  - '-I./rootstraps/4.0/usr/include/telephony/'
  - '-I./rootstraps/4.0/usr/include/web/'
  - '-I./rootstraps/4.0/usr/include/yaca/'

  # include efl directories
  - '-I./rootstraps/4.0/usr/include/evas-1/'
  - '-I./rootstraps/4.0/usr/include/efl-1/'
  - '-I./rootstraps/4.0/usr/include/eo-1/'
  - '-I./rootstraps/4.0/usr/include/eina-1/'
  - '-I./rootstraps/4.0/usr/include/eina-1/eina/'
  - '-I./rootstraps/4.0/usr/include/emile-1/'
  - '-I./rootstraps/4.0/usr/include/ecore-imf-1/'

enums:
  rename:
    '_+(.*)': '$1'
